xeroxproject/xeroxapp/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.login, name="login"),
    path("logout/", views.login, name="login"),
    path("pdflist/", views.ownerpdf, name="ownerpdf"),
    path("pdfliststudent/", views.studentpdf, name="studentpdf"),
    path("ownerorder/", views.ownerorder, name="ownerorder"),
    path("addpdf/", views.addPDF, name="addPDF"),


    

]

xeroxproject/xeroxproject/urls.py
from django.contrib import admin
from django.urls import path, include
from xeroxapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(("xeroxapp.urls", "xerox_app"), namespace="xeroxapp")),
    path("", include("django.contrib.auth.urls"))
]

xeroxproject/xeroxapp/models.py
#IF THIS PAGE IS MODIFIED, REMEMBER TO EXCECUTE THE FOLLOWING COMMANDS IN PYTHON SHELL
#python manage.py makemigrations xeroxapp
#python manage.py migrate

from django.db import models

# Create your models here.

class ownerPDFlist(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
    #Meta data for ownerPDFlist
    #Else the display name in the admin dashboard will be "Owner pd flists"
    class Meta:
        verbose_name_plural="ownerPDFlist"
    
class PDF(models.Model):
    ownerPDFlist=models.ForeignKey(ownerPDFlist, on_delete=models.CASCADE) #use 'o.pdf_set.all()' to access all the pdfs present
    Slno=models.IntegerField()
    name=models.CharField(max_length=300)
    price = models.IntegerField()


    def __str__(self):
        return f"{self.Slno} - {self.name} - {self.price}"
    
    #Meta data for PDF
    #Else the display name in the admin dashboard will be "Pdfs"
    class Meta:
        verbose_name="PDF"
        verbose_name_plural="PDFs"



class studentPDFlist(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
    #Meta data for studentPDFlist
    #Else the display name in the admin dashboard will be "Student pd flists"
    class Meta:
        verbose_name_plural="studentPDFlist"
    
class studentPDF(models.Model):
    studentPDFlist=models.ForeignKey(studentPDFlist, on_delete=models.CASCADE) #use 'o.pdf_set.all()' to access all the pdfs present
    Slno=models.IntegerField()
    name=models.CharField(max_length=300)
    price = models.IntegerField()
    order = models.BooleanField()


    def __str__(self):
        return f"{self.Slno} - {self.name} - {self.price} - {self.order}"
    
    #Meta data for studentPDF
    #Else the display name in the admin dashboard will be "studentPdfs"
    class Meta:
        verbose_name="studentPDF"
        verbose_name_plural="studentPDFs"


class OwnerOrder(models.Model):
    ownerPDFlist=models.ForeignKey(ownerPDFlist, on_delete=models.CASCADE)
    Slno=models.IntegerField()
    name=models.CharField(max_length=300)
    price = models.IntegerField()
    completed = models.BooleanField()

    def __str__(self):
        return f"{self.Slno} - {self.name} - {self.price} - {self.completed}"

    class Meta:
        verbose_name_plural="OwnerOrder"



class CredentialList(models.Model):
    name = models.CharField(max_length = 200)
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = "CredentialList"
        
    
class StudentCredentials(models.Model):
    CredentialList=models.ForeignKey(CredentialList, on_delete=models.CASCADE)
    regno = models.CharField(max_length = 10)
    password = models.CharField(max_length = 20)

    def __str__(self):
        return self.regno
    
    class Meta:
        verbose_name_plural = "StudentCredentials"



class OwnerCredentials(models.Model):
    CredentialList=models.ForeignKey(CredentialList, on_delete=models.CASCADE)
    regno = models.CharField(max_length = 10)
    password = models.CharField(max_length = 20)

    def __str__(self):
        return self.regno
    
    class Meta:
        verbose_name_plural = "OwnerCredentials"

xeroxproject/xeroxapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
from django.forms import ModelForm
from .models import StudentCredentials, CredentialList, OwnerCredentials

class LoginForm(forms.Form):
    username = forms.CharField(
        label='regno',
        widget=forms.TextInput(attrs={'placeholder': 'Enter registration number'}),
    )
    password = forms.CharField(
        label='password',
        widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}),
    )
    class Meta:
        model = StudentCredentials
        fields = ["regno", "password"]


        

    

xeroxproject/xeroxapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import ownerPDFlist, PDF, studentPDFlist, studentPDF, OwnerOrder, StudentCredentials, OwnerCredentials
from .addpdf import AddPDF
from .forms import LoginForm
from django.contrib.auth import authenticate, login, logout

# Create your views here.




def ownerpdf(response):
    p = ownerPDFlist.objects.get(name = "Notes")
    return render(response, "pdflist.html", {"p":p})

def studentpdf(response):
    p = studentPDFlist.objects.get(name = "Notes")
    if response.method == "POST":
        print(response.POST)
        if response.POST.get("order"):
            for pdf in p.studentpdf_set.all():
                if response.POST.get(pdf.name) == "ordered":
                    s = pdf.Slno
                    n = pdf.name
                    p = pdf.price
                    owner_pdf_list, created = ownerPDFlist.objects.get_or_create(name="Orders")
                    o = OwnerOrder(Slno = s, name = n, price = p, completed = False, ownerPDFlist=owner_pdf_list)
                    o.save()
        
    return render(response, "pdfliststudent.html", {"p":p})



def ownerorder(response):
    p = ownerPDFlist.objects.get(name = "Orders")
    if response.method == "POST":
        print(response.POST)
        if response.POST.get("save"):
            for pdf in p.ownerorder_set.all():
                if response.POST.get("c" + str(pdf.id)) == "completed":
                    pdf.completed = True
                    pdf.save()
                else:
                    pdf.completed = False
                    pdf.save()

        if response.POST.get("delete"):
            for pdf in p.ownerorder_set.all():
                if pdf.completed == True:
                    pdf.delete()





    return render(response, "ownerorder.html", {"p":p})


def addPDF(response):
    if response.method == "POST":
        form = AddPDF(response.POST)
        print(response.POST)

        if form.is_valid():
            s = form.cleaned_data["Slno"]
            n = form.cleaned_data["name"]
            p = form.cleaned_data["price"]
            # Get or create ownerPDFlist (change the condition as needed)
            owner_pdf_list, created = ownerPDFlist.objects.get_or_create(name="Notes")
            student_pdf_list, created = studentPDFlist.objects.get_or_create(name="Notes")
            
            # Create a new PDF instance associated with the ownerPDFlist
            pdf = PDF(Slno=s, name=n, price=p, ownerPDFlist=owner_pdf_list)
            studentpdf = studentPDF(Slno=s, name=n, price=p, order=False, studentPDFlist=student_pdf_list)
            pdf.save()
            studentpdf.save()
        return HttpResponseRedirect("/addpdf")
    else:
        form = AddPDF()
    return render(response, "addpdf.html", {"form":form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            regno = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = StudentCredentials.objects.filter(regno=regno, password=password).first()
            

            if user:
                return HttpResponseRedirect('/pdfliststudent')
            else:
                user = OwnerCredentials.objects.filter(regno=regno, password=password).first()
                if user:
                    return HttpResponseRedirect('/pdflist')
                return render(request, 'login.html', {'error_message' : 'Invalid credentials. Please try again.'})

    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})



xeroxproject/xeroxapp/templates/addpdf.html
{% extends "baseowner.html" %}

{% block title %} Add PDF {% endblock %}

{% block content %}
Add a PDF
<form method = "post" action = "{% url 'xeroxapp:addPDF' %}">
	{% csrf_token %}
	{{form.as_p}}
	<button type = "submit" name = "Add" value = "Add">Add PDF</button>
	
</form>

{% endblock %}

xeroxproject/xeroxapp/templates/baseowner.html
<html>
<head>
	<style type = "text/css">
		.sidenav {
			height:100%;
			width:160px;
			position:fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#111;
			overflow-x: :hidden;
			padding-top:20px;
		}

		.sidenav a{
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size: 25px;
			color: #818181;
			display:block;

		}

		.sidenav a:hover{
			color:#f1f1f1;
		}

		.main{
			margin-left:160px;
			padding: 0px 10px;
		}

	</style>
	<title>{% block title %}Base site{% endblock %}</title>
</head>

<body>
	<div class="sidenav">
		<a href="/pdflist">View PDFs</a>
		<a href="/addpdf">Add PDF</a>
		<a href="/ownerorder">View Orders</a>
		<a href="/logout">Logout</a>
	</div>

	<div id="content", name="content", class="main">
		{% block content %}
				
		{% endblock %}
		
	</div>
	
</body>


</html>

xeroxproject/xeroxapp/templates/basestudent.html
<html>
<head>
	<style type = "text/css">
		.sidenav {
			height:100%;
			width:160px;
			position:fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#5a6484;
			overflow-x: :hidden;
			padding-top:20px;
		}

		.sidenav a{
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size: 25px;
			color: #c4c4df;
			display:block;

		}

		.sidenav a:hover{
			color:#e7e7e9;
		}

		.main{
			margin-left:160px;
			padding: 0px 10px;
		}

	</style>
	<title>{% block title %}Base site{% endblock %}</title>
</head>

<body>
	<div class="sidenav">
		
		<a href="/pdfliststudent">View PDFs</a>
		<a href="/logout">Logout</a>
	</div>

	<div id="content", name="content", class="main">
		{% block content %}
				
		{% endblock %}
		
	</div>
	
</body>


</html>

xeroxproject/xeroxapp/templates/login.html
<html>
<head>
<title>Login Page</title>
</head>


<body>
<form method="post" class="from-group" action = "{% url 'xeroxapp:login' %}">
    {% csrf_token %}
    <label for="regno" name="regno" aria-placeholder="Enter your registration number">Registration Number:</label><br>
    <input type="text" for ="username" name="username"></input>
    <br>
    <label for="password" name="'password" aria-placeholder="Enter your password">Password:</label><br>
    <input type="text" for="password" name="password"></input>
    <br>
    <button type="submit">Login</button>

</form>

{{error_message}}

</body>

</html>

xeroxproject/xeroxapp/templates/ownerorder.html
{% extends "baseowner.html" %}
{% block title %}Orders{% endblock %}
{% block content %}<h1>Orders</h1>

<form method="post" action="#">
	{% csrf_token %}
	<table border="1">
		<tr><th>Sl no.</th><th>Name</th><th>Price</th><th>Completed</th></tr>
	{% for pdf in p.ownerorder_set.all %}
		<tr><td>{{pdf.Slno}}</td><td>{{pdf.name}}</td><td>{{pdf.price}}</td>
			<td>
			{% if pdf.completed == True %}
				<input type = "checkbox", value="completed", name="c{{pdf.id}}" checked>
			{% else %}
				<input type = "checkbox", value="completed", name="c{{pdf.id}}">
			{% endif %}

			</td></tr>

	{% endfor %}
	</table>

  <br>

	<button type="submit", value="save", name="save">Save</button>
	<button type="submit", value="delete", name="delete">Delete</button>

</form>
{% endblock %}

xeroxproject/xeroxapp/templates/pdflist.html
{% extends "baseowner.html" %}
{% block title %}PDF List{% endblock %}
{% block content %}<h1>Available PDFs</h1>


<table border="1">
	<tr><th>Sl no.</th><th>Name</th><th>Price</th></tr>
{% for pdf in p.pdf_set.all %}
	<tr><td>{{pdf.Slno}}</td><td>{{pdf.name}}</td><td>{{pdf.price}}</td></tr>

{% endfor %}
</table>


{% endblock %}

xeroxproject/xeroxapp/templates/pdfliststudent.html
{% extends "basestudent.html" %}
{% block title %}PDF List{% endblock %}
{% block content %}<h1>Available PDFs</h1>

<form method="post" action="#">
	{% csrf_token %}
	<table border="1">
		<tr><th>Sl no.</th><th>Name</th><th>Price</th><th>Order</th></tr>
	{% for pdf in p.studentpdf_set.all %}
		<tr><td>{{pdf.Slno}}</td><td>{{pdf.name}}</td><td>{{pdf.price}}</td>
			<td>
			{% if pdf.order == True %}
				<input type = "checkbox", value="ordered", name="{{pdf.name}}" checked>
			{% else %}
				<input type = "checkbox", value="ordered", name="{{pdf.name}}">
			{% endif %}

			</td></tr>

	{% endfor %}
	</table>
	<br>

	<button type="submit", value = "order", name="order">Add to cart</button>

</form>
{% endblock %}

xeroxproject/xeroxapp/templates/xeroxapp/addpdf.html
{% extends "xeroxapp/base.html" %}

{% block title %} Add PDF {% endblock %}

{% block content %}
Add a PDF
<form method = "post" action = "{% url 'xeroxapp:addPDF' %}">
	{% csrf_token %}
	{{form.as_p}}
	<button type = "submit", name = "Add">Add PDF</button>
	
</form>

{% endblock %}

xeroxproject/xeroxapp/templates/xeroxapp/base.html
<html>
<head>
	<style type = "text/css">
		.sidenav {
			height:100%;
			width:160px;
			position:fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#111;
			overflow-x: :hidden;
			padding-top:20px;
		}

		.sidenav a{
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size: 25px;
			color: #818181;
			display:block;

		}

		.sidenav a:hover{
			color:#f1f1f1;
		}

		.main{
			margin-left:160px;
			padding: 0px 10px;
		}

	</style>
	<title>{% block title %}Base site{% endblock %}</title>
</head>

<body>
	<div class="sidenav">
		<a href="/pdflist">View PDFs</a>
		<a href="/addpdf">Add PDF</a>
	</div>

	<div id="content", name="content", class="main">
		{% block content %}
			
		{% endblock %}
	</div>
	
</body>


</html>

xeroxproject/xeroxapp/templates/xeroxapp/home.html
{% extends "xeroxapp/base.html" %}
{% block title %} Home Page {% endblock %}
{% block content %}<h1>Welcome!</h1>{% endblock %}